cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'autoconf'
brew 'openssl'
brew 'htop'
brew 'libyaml'
brew 'mercurial'
brew 'node'
brew 'phantomjs'
brew 'pkg-config'
brew 'postgresql'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'redis'
brew 'unrar'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

cask 'cyberduck'
cask 'git'
cask 'gitx'
cask 'iterm2'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
